"""Seed content for Homeland Group Mohali — placeholder-yet-realistic data.
All content is fully editable via the admin dashboard.
"""

# ---- Image pools (Unsplash luxury real-estate) ----
IMG = {
    "regalia_hero": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    "heights_hero": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80",
    "cp67_hero": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80",
    "globalpark_hero": "https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=1600&q=80",
    "newchd_hero": "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1600&q=80",
    "amritsar_hero": "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=80",
    "yps_hero": "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=1600&q=80",
    "phase8_hero": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80",
}

GALLERY_RES = [
    "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
]
GALLERY_COM = [
    "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80",
]

VIDEO = "https://www.youtube.com/embed/1O6Qstncpnc"

PROJECTS = [
    {
        "slug": "homeland-regalia",
        "name": "Homeland Regalia",
        "tagline": "The Most Powerful Address in Punjab — Reserved for the Exclusive Few.",
        "status": "ONGOING",
        "possession": "Possession by Dec 2026",
        "location": "Sector 77, Mohali",
        "full_address": "Sector 77, International Airport Road, Mohali, Punjab 160070",
        "city": "Mohali",
        "type": "Residential",
        "unit_types": ["3 BHK", "4 BHK", "5 BHK"],
        "key_units": "6 Iconic Towers · 3/4/5 BHK Sky Residences",
        "price_range": "\u20b91.85 Cr onwards",
        "rera_numbers": ["PBRERA-SAS81-PR0757"],
        "rera_registered_date": "2021-08-12",
        "rera_certificate_url": "",
        "amenities": [
            "World-class Concierge Services", "All-season Indoor Pool", "State-of-the-art Fitness Zones",
            "Landscaped Gardens", "Grand Clubhouse", "Children's Play Areas", "Private Locker Room",
            "Indoor AC Basketball Court", "Outdoor Gym", "Yoga & Meditation Deck", "Full-size Tennis Court",
            "Sun-bathing Deck", "Outdoor Cricket Pitch", "Club Deck with Bar & Cafe", "Reflexology Plaza",
        ],
        "description": "Experience ultra-luxury living at Homeland Regalia, a premium residential landmark designed as a true symbol of royalty. With six iconic towers, it offers a royal lifestyle with top-tier amenities and effortless access to leading educational institutions, healthcare, shopping and business hubs. Architectural brilliance meets refined interiors and thoughtfully designed common areas amid lush green surroundings.",
        "highlights": [
            "6 iconic towers with panoramic Shivalik views",
            "3-side open sky residences with private decks",
            "Located on International Airport Road, Sector 77",
            "Grand triple-height entrance lobby",
        ],
        "hero_image": IMG["regalia_hero"],
        "gallery": GALLERY_RES,
        "video_url": VIDEO,
        "brochure_url": "https://homelandregalia.com",
        "map_lat": 30.6788,
        "map_lng": 76.7369,
        "landmarks": ["3 min to Mohali International Airport Road", "10 min to ISB Mohali", "12 min to Fortis Hospital"],
        "featured": True,
        "hot_selling": True,
        "order": 1,
    },
    {
        "slug": "homeland-heights",
        "name": "Homeland Heights",
        "tagline": "Elevated Living in the Heart of Mohali.",
        "status": "DELIVERED",
        "possession": "Delivered 2018",
        "location": "Sector 70, Mohali",
        "full_address": "Sector 70, Mohali, Punjab 160071",
        "city": "Mohali",
        "type": "Residential",
        "unit_types": ["2 BHK", "3 BHK"],
        "key_units": "Spacious 2 & 3 BHK Premium Apartments",
        "price_range": "\u20b985 Lac onwards",
        "rera_numbers": ["PBRERA-SAS79-PR0231"],
        "rera_registered_date": "2017-03-20",
        "rera_certificate_url": "",
        "amenities": [
            "Landscaped Central Green", "Community Clubhouse", "Gymnasium", "Kids Play Area",
            "24x7 Security", "Power Backup", "Covered Parking", "Jogging Track",
        ],
        "description": "Homeland Heights offers spacious apartments with world-class amenities and excellent connectivity in the heart of Mohali. Successfully delivered in 2018, it remains a benchmark for quality construction and thoughtful community living, home to hundreds of happy families.",
        "highlights": [
            "Successfully delivered & fully occupied",
            "Prime Sector 70 location",
            "Vaastu-compliant spacious layouts",
            "Well-connected to Chandigarh & Airport",
        ],
        "hero_image": IMG["heights_hero"],
        "gallery": GALLERY_RES,
        "video_url": VIDEO,
        "brochure_url": "https://www.homelandgroup.org",
        "map_lat": 30.7046,
        "map_lng": 76.7179,
        "landmarks": ["5 min to Sector 70 Market", "8 min to Chandigarh border", "10 min to Mohali Bus Stand"],
        "featured": False,
        "hot_selling": False,
        "order": 2,
    },
    {
        "slug": "homeland-unity-cp67",
        "name": "Homeland Unity CP67",
        "tagline": "Where Business Meets Lifestyle.",
        "status": "DELIVERED",
        "possession": "Operational",
        "location": "Sector 67, Mohali",
        "full_address": "CP67 Mall, Sector 67, Mohali, Punjab 160062",
        "city": "Mohali",
        "type": "Commercial",
        "unit_types": ["Retail Shops", "Food Court", "Office Suites"],
        "key_units": "Retail · F&B · Standardized Business Spaces",
        "price_range": "On Request",
        "rera_numbers": ["PBRERA-SAS80-PR0198"],
        "rera_registered_date": "2016-11-05",
        "rera_certificate_url": "",
        "amenities": [
            "High-street Retail", "Multi-brand Food Hub", "Ample Parking", "Central Atrium",
            "Escalators & Lifts", "24x7 Security", "Power Backup", "Footfall-rich Location",
        ],
        "description": "CP67 is a landmark commercial destination offering standardized business spaces, high-street retail and a vibrant food hub. A thriving hub of activity, it brings together shopping, dining and business under one iconic address in the heart of Mohali.",
        "highlights": [
            "Established retail & F&B destination",
            "High daily footfall",
            "Located in busy Sector 67",
            "Proven rental returns",
        ],
        "hero_image": IMG["cp67_hero"],
        "gallery": GALLERY_COM,
        "video_url": VIDEO,
        "brochure_url": "https://www.homelandgroup.org",
        "map_lat": 30.7011,
        "map_lng": 76.7285,
        "landmarks": ["In Sector 67 Mohali", "5 min to Phase 7 Market", "10 min to Chandigarh"],
        "featured": False,
        "hot_selling": False,
        "order": 3,
    },
    {
        "slug": "homeland-global-park",
        "name": "Homeland Global Park",
        "tagline": "A Global-Scale Destination for Retail, Business & Lifestyle.",
        "status": "ONGOING",
        "possession": "Possession by 2027",
        "location": "New Chandigarh",
        "full_address": "IT City Road, New Chandigarh, Punjab",
        "city": "New Chandigarh",
        "type": "Mixed-Use",
        "unit_types": ["Ultra-luxury Mall", "Retail", "Business Suites"],
        "key_units": "Global Retail · High-end Business Suites · Entertainment",
        "price_range": "\u20b942 Lac onwards",
        "rera_numbers": ["PBRERA-SAS82-PR0921"],
        "rera_registered_date": "2022-06-18",
        "rera_certificate_url": "",
        "amenities": [
            "Ultra-luxury Mall", "Global Retail Brands", "High-end Business Suites", "Multiplex & Entertainment",
            "Fine-dining Zones", "Smart Parking", "Green Boulevards", "Grand Central Plaza",
        ],
        "description": "Homeland Global Park is an ultra-luxury mixed-use destination bringing global retail brands, high-end business suites and world-class entertainment together in North India. Designed at a global scale, it is set to redefine the region's commercial and lifestyle landscape.",
        "highlights": [
            "Ultra-luxury mall with global brands",
            "Prime IT City / New Chandigarh location",
            "Mixed-use retail + business + entertainment",
            "Investment-grade commercial spaces",
        ],
        "hero_image": IMG["globalpark_hero"],
        "gallery": GALLERY_COM,
        "video_url": VIDEO,
        "brochure_url": "https://www.homelandgroup.org",
        "map_lat": 30.7833,
        "map_lng": 76.6667,
        "landmarks": ["IT City New Chandigarh", "Near Medicity", "15 min to PGI Chandigarh"],
        "featured": True,
        "hot_selling": True,
        "order": 4,
    },
    {
        "slug": "homeland-new-chandigarh",
        "name": "Homeland New Chandigarh",
        "tagline": "Modern Living Amidst Nature's Serenity.",
        "status": "ONGOING",
        "possession": "Possession by Jun 2027",
        "location": "Mullanpur, New Chandigarh",
        "full_address": "Mullanpur, New Chandigarh, Punjab 140901",
        "city": "New Chandigarh",
        "type": "Residential",
        "unit_types": ["2 BHK", "3 BHK", "4 BHK"],
        "key_units": "Premium 2/3/4 BHK Residences",
        "price_range": "\u20b91.10 Cr onwards",
        "rera_numbers": ["PBRERA-SAS83-PR1044"],
        "rera_registered_date": "2023-01-30",
        "rera_certificate_url": "",
        "amenities": [
            "Clubhouse", "Swimming Pool", "Landscaped Gardens", "Gymnasium", "Indoor Games",
            "Amphitheatre", "Jogging & Cycling Track", "Kids Play Zone", "24x7 Security",
        ],
        "description": "Nestled in the green, planned township of New Chandigarh (Mullanpur), Homeland New Chandigarh offers modern residences surrounded by nature. Enjoy premium amenities, wide open spaces and clean air at the foothills of the Shivaliks, with excellent connectivity to Chandigarh.",
        "highlights": [
            "Foothills of the Shivaliks",
            "Planned green township of New Chandigarh",
            "Low-density premium living",
            "Close to Medicity & educational hubs",
        ],
        "hero_image": IMG["newchd_hero"],
        "gallery": GALLERY_RES,
        "video_url": VIDEO,
        "brochure_url": "https://www.homelandchandigarh.in",
        "map_lat": 30.7900,
        "map_lng": 76.6900,
        "landmarks": ["Mullanpur New Chandigarh", "Near Tata Camelot", "10 min to Chandigarh"],
        "featured": False,
        "hot_selling": False,
        "order": 5,
    },
    {
        "slug": "homeland-amritsar",
        "name": "Homeland Amritsar",
        "tagline": "A New Icon Rising in the Holy City.",
        "status": "UPCOMING",
        "possession": "Launching Soon",
        "location": "Ranjit Avenue, Amritsar",
        "full_address": "Ranjit Avenue, Amritsar, Punjab 143001",
        "city": "Amritsar",
        "type": "Mixed-Use",
        "unit_types": ["To be announced"],
        "key_units": "Premium Residences & Retail (Details Coming Soon)",
        "price_range": "Coming Soon",
        "rera_numbers": ["RERA Application In Process"],
        "rera_registered_date": "",
        "rera_certificate_url": "",
        "amenities": ["Premium Clubhouse", "Landscaped Greens", "Retail Promenade", "Smart Security"],
        "description": "Homeland Amritsar marks the Group's prestigious entry into the holy city at the coveted Ranjit Avenue address. A landmark mixed-use development is being planned to bring premium living and retail to Amritsar. Full details will be revealed at launch.",
        "highlights": [
            "Prime Ranjit Avenue location",
            "Mixed-use premium development",
            "Group's flagship entry into Amritsar",
            "Register early for priority allotment",
        ],
        "hero_image": IMG["amritsar_hero"],
        "gallery": GALLERY_RES,
        "video_url": "",
        "brochure_url": "",
        "map_lat": 31.6340,
        "map_lng": 74.8723,
        "landmarks": ["Ranjit Avenue Amritsar", "Near District Shopping Complex", "15 min to Golden Temple"],
        "featured": False,
        "hot_selling": False,
        "order": 6,
    },
    {
        "slug": "homeland-yps-chowk-mohali",
        "name": "Homeland Commercial cum Residential — YPS Chowk Mohali",
        "tagline": "An Ultra-Luxury Address Adjacent to Chandigarh.",
        "status": "UPCOMING",
        "possession": "Pre-Launch 2026",
        "location": "YPS Chowk, Mohali",
        "full_address": "Opposite YPS School, Chandigarh Border, Mohali, Punjab",
        "city": "Mohali",
        "type": "Mixed-Use",
        "unit_types": ["3+1 BHK", "4+1 BHK", "Penthouses"],
        "key_units": "5.5-acre Ultra-luxury Residences + Commercial",
        "price_range": "\u20b970 Cr / Acre (indicative)",
        "rera_numbers": ["RERA Application In Process"],
        "rera_registered_date": "",
        "rera_certificate_url": "",
        "amenities": [
            "Temperature-controlled Indoor Pool", "Private Clubhouse with Sky Lounge", "Fully Equipped Gymnasium",
            "Business Lounge", "Banquet Facilities", "Concierge Service", "Multi-tier Biometric & CCTV Security",
            "Multi-level Parking", "Curated Podium Landscape",
        ],
        "description": "Homeland YPS Mohali is a 5.5-acre ultra-luxury commercial-cum-residential development strategically located adjacent to Chandigarh at the prominent YPS Chowk. Offering exclusive 3+1 & 4+1 BHK residences and penthouses with premium amenities, it promises one of the region's most prestigious addresses.",
        "highlights": [
            "5.5-acre landmark, adjacent to Chandigarh",
            "Opposite YPS School — prime border location",
            "Ultra-luxury residences + high-street commercial",
            "Sky lounge, concierge & multi-tier security",
        ],
        "hero_image": IMG["yps_hero"],
        "gallery": GALLERY_RES,
        "video_url": "",
        "brochure_url": "",
        "map_lat": 30.7267,
        "map_lng": 76.7392,
        "landmarks": ["YPS Chowk, Chandigarh border", "Opposite YPS School", "5 min to Chandigarh Sector 51"],
        "featured": False,
        "hot_selling": False,
        "order": 7,
    },
    {
        "slug": "homeland-group-housing-phase-8",
        "name": "Homeland Group Housing — Phase 8 (near Fortis Hospital)",
        "tagline": "Premium Group Housing in the Heart of Phase 8.",
        "status": "UPCOMING",
        "possession": "Launching Soon",
        "location": "Phase 8, Mohali",
        "full_address": "Phase 8, near Fortis Hospital, Mohali, Punjab 160062",
        "city": "Mohali",
        "type": "Residential",
        "unit_types": ["3 BHK", "4 BHK"],
        "key_units": "Premium Group Housing Residences (Details Coming Soon)",
        "price_range": "Coming Soon",
        "rera_numbers": ["RERA Application In Process"],
        "rera_registered_date": "",
        "rera_certificate_url": "",
        "amenities": ["Clubhouse", "Swimming Pool", "Gymnasium", "Landscaped Greens", "Kids Play Area", "24x7 Security"],
        "description": "An upcoming premium group housing development in the sought-after Phase 8, Mohali — moments from Fortis Hospital and the city's key business and lifestyle destinations. Thoughtfully designed residences with modern amenities are being planned. Register your interest for early access.",
        "highlights": [
            "Prime Phase 8 location near Fortis Hospital",
            "Excellent healthcare & connectivity",
            "Premium group housing residences",
            "Register early for priority allotment",
        ],
        "hero_image": IMG["phase8_hero"],
        "gallery": GALLERY_RES,
        "video_url": "",
        "brochure_url": "",
        "map_lat": 30.7112,
        "map_lng": 76.6994,
        "landmarks": ["Phase 8 Mohali", "Near Fortis Hospital", "5 min to Phase 8 Industrial Area"],
        "featured": False,
        "hot_selling": False,
        "order": 8,
    },
]

SITE_CONTENT = {
    "key": "main",
    "brand_name": "Homeland Group",
    "brand_tagline": "Crafting Iconic Addresses Across Punjab & the Tricity",
    "founding_year": 2013,
    "history_intro": "Founded in 2013, Homeland Group has grown into one of the most trusted names in real estate across Chandigarh, Mohali and Punjab. With over a decade of legacy and 1,000+ happy families, we are defined by iconic architecture, uncompromising quality and a commitment to timely delivery. Every Homeland address is a promise — of craftsmanship, of trust, and of a life elevated.",
    "milestones": [
        {"year": "2013", "title": "The Foundation", "description": "Homeland Group is founded in Mohali with a vision to redefine premium living in the Tricity."},
        {"year": "2018", "title": "Landmark Deliveries", "description": "Homeland Heights & Homeland Regalia successfully delivered, setting new benchmarks in quality."},
        {"year": "2020", "title": "Commercial Expansion", "description": "CP67 establishes itself as a thriving retail & business destination in Mohali."},
        {"year": "2022", "title": "Going Global", "description": "Homeland Global Park launched — an ultra-luxury mixed-use destination for North India."},
        {"year": "2024", "title": "1,000+ Happy Families", "description": "Crossed a milestone of over 1,000 delivered homes and a decade of trust."},
        {"year": "2026", "title": "New Horizons", "description": "Expanding to Amritsar, YPS Chowk & Phase 8 with landmark upcoming developments."},
    ],
    "benchmark_kpis": [
        {"label": "Years of Legacy", "value": "13+", "description": "A decade-plus of trusted development", "icon": "award"},
        {"label": "Happy Families", "value": "1,000+", "description": "Homes delivered across the Tricity", "icon": "users"},
        {"label": "Projects Delivered", "value": "10+", "description": "Residential & commercial landmarks", "icon": "building-2"},
        {"label": "On-time Delivery", "value": "100%", "description": "Committed to timely possession", "icon": "clock"},
        {"label": "Sq. Ft. Developed", "value": "5M+", "description": "Of premium living & retail space", "icon": "ruler"},
        {"label": "RERA Compliant", "value": "Certified", "description": "Every project registered & transparent", "icon": "shield-check"},
    ],
    "vision_statement": "To be the leading real estate developer in Punjab and the Tricity — delivering premium, luxury projects with world-class amenities and unwavering commitment to timely delivery.",
    "vision_pillars": [
        {"title": "Iconic Architecture", "description": "Design-led landmarks that stand the test of time and elevate every skyline."},
        {"title": "Uncompromising Quality", "description": "Best-in-class materials, engineering and finishes across every square foot."},
        {"title": "Timely Delivery", "description": "A disciplined execution culture ensuring homes are handed over on schedule."},
        {"title": "Customer First", "description": "Transparent, RERA-compliant processes and lifelong relationships with our families."},
        {"title": "Sustainable Living", "description": "Green, thoughtfully-planned communities designed for a better tomorrow."},
    ],
    "contact_phone": "+91 98155 00000",
    "contact_email": "sales@homelandgroup.org",
    "contact_whatsapp": "+91 98155 00000",
    "contact_address": "Corporate Office, Sector 77, Mohali, Punjab 160070",
    "social": {
        "facebook": "https://facebook.com/homelandgroup",
        "instagram": "https://instagram.com/homelandgroup",
        "linkedin": "https://linkedin.com/company/homelandgroup",
        "youtube": "https://youtube.com/@homelandgroup",
    },
}

TEAM = [
    {"name": "Rajinder Singh", "role": "Chairman & Managing Director", "expertise": "Visionary leadership with 25+ years in real estate development.", "bio": "As the driving force behind Homeland Group, Rajinder Singh has led the company from a single project to a portfolio of iconic landmarks across the Tricity, guided by an unwavering commitment to quality and trust.", "image": "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80", "order": 1},
    {"name": "Aman Preet", "role": "Chief Executive Officer", "expertise": "Strategy, growth and operational excellence across all verticals.", "bio": "Aman Preet oversees the Group's strategic direction, scaling operations while preserving the craftsmanship and customer-first ethos that define every Homeland address.", "image": "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80", "order": 2},
    {"name": "Vikram Sethi", "role": "Head of Projects", "expertise": "End-to-end project execution and on-time delivery.", "bio": "Vikram leads project planning and delivery, ensuring engineering excellence and adherence to timelines across residential and commercial developments.", "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80", "order": 3},
    {"name": "Neha Kapoor", "role": "Head of Sales", "expertise": "Customer experience, channel partnerships and NRI relations.", "bio": "Neha heads the sales organisation, building lasting relationships with home-buyers, investors and channel partners across India and abroad.", "image": "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80", "order": 4},
    {"name": "Arjun Malhotra", "role": "Head of Design", "expertise": "Architecture, interiors and design innovation.", "bio": "Arjun leads the design studio, translating the Group's vision into iconic, functional and future-ready spaces that stand apart.", "image": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80", "order": 5},
]

FAQS = [
    {"q": "What does RERA registration mean for buyers?", "a": "RERA (Real Estate Regulatory Authority) registration ensures a project is legally compliant, transparent and accountable. Every Homeland project displays its RERA number and is registered with the Punjab RERA authority."},
    {"q": "How can I download a project brochure?", "a": "Visit any project detail page or the Brochure Center and click 'Download Brochure'. You may optionally share your contact details so our team can assist you further."},
    {"q": "Do you assist NRI buyers?", "a": "Yes. Our dedicated NRI desk assists with documentation, virtual tours and end-to-end purchase support. Submit an enquiry and our team will reach out."},
    {"q": "Can I schedule a site visit?", "a": "Absolutely. Use the enquiry form or call our sales team to schedule a guided site visit at your preferred time."},
    {"q": "Are home loans available on Homeland projects?", "a": "Yes, our projects are approved by leading banks and financial institutions. Our team can connect you with loan partners for the best rates."},
]
